### ISSUE TITLE
Screen-shot creation not working at all after upgrade

### ISSUE THREAD

**Issue by svx** [plone/papyrus#118]
Another upgrade issue:

If you upgrade the buildout to the latest versions of robot-framework and friends:

```
plone.app.robotframework = 0.9.16
robotframework = 3.0
robotframework-selenium2library = 1.8.0
robotframework-selenium2screenshots = 0.7.2
robotsuite = 1.7.0
selenium = 3.0.1
sphinxcontrib-robotframework = 0.6.1
```

You are not able to do any screen-shots with phantom, firefox or chrome at all, you get this [firefox example]:

![pap-screen-error](https://cloud.githubusercontent.com/assets/358860/20594460/9ee615c6-b236-11e6-9f44-7a5cab77cf55.png)

**Comment by svx** [comment]
Fixed, at least for phantomjs with re-installing phantomjs.

Great ! 

Still I do not like this, way tooo buggy and time consuming ....

**Comment by polyester** [comment]
I am beginning to agree. The whole robotframework-screenshot idea is cool, but it is 

- very fragile, it breaks with almost any minor version upgrade, not of Plone but of the supporting tech
- too many moving parts (webdriver for the various browsers, selenium, robotframework and the various addons)
- requires a whole different skillset (meaning docs people have to fight with selenium/robot error messages, which usually can only be solved if you are a programmer familiar with the technology)
- writing the screenshot-tests is also not easy to do for docwriters or casual contributors
- therefore adds a lot of cognitive load, which is better spent actually **writing** documentation...


However, returning to static screenshots leaves the question how to keep those up to date, when new functionality is added, or even simply because layout/css has changed.

That is also a considerable amount of work, and would need to be worked into some kind of process to make sure it is actually done when a new 5.x version comes out; it would be justifiable to *not* do it for every 5.0.x version, or only on a 'best effort' basis...

**Comment by svx** [comment]
Not an issue anymore, screen-shots are now in CMFPlone
