### ISSUE TITLE
buildout.cfg plone 3 branch

### ISSUE THREAD

**Issue by svx** [plone/papyrus#34]
buildout.cfg in the plone3 branch is using plone 4 for screen shots, this should be fixed

**Comment by svx** [comment]
how much time and effort we want to invest into Plone 3 docs ?

**Comment by polyester** [comment]
zero.

**Comment by svx** [comment]
ok assuming that, I will close all open issues for the 3er branch then ?

**Comment by polyester** [comment]
yep, unless it something catastrophic, like "we can't deploy them at all". Even then, I would consider them 'frozen' for now.  Only things may get added to them, for instance when we find stuff we want to get rid of in the 4/5 branches because it's old.
But we're not upgrading, maintaining, improving the 3.x docs anymore, they are reference material 'as-is'.
