### ISSUE TITLE
include plone.app.event

### ISSUE THREAD

**Issue by jensens** [plone/papyrus#67]
see plone/plone.app.event#180:
cite from comment by @pbauer 

here are the things you need to know to include them in docs.plone.org:
- the docs are here: https://github.com/plone/plone.app.event/tree/master/docs
- on docs.plone.org they should be after http://docs.plone.org/develop/index.html#plone-app-contentlisting
- include them for 4 and 5

**Comment by polyester** [comment]
Needs review first. Plone.app.event uses a whole slew of sphinx extensions:
extensions = [
    'sphinx.ext.doctest',
    'sphinx.ext.coverage',
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.autosummary',
]

some of which pull in the entire codebase, and thereby making the translation and other setup more difficult.

Whether things like autodoc are really helpful is matter for debate: 
- developers usually think they are (for accuracy and completeness, but mainly because they think they have to write less documentation ;-)
- documentarians think automated lists are at best good for appendices, not a replacement for proper docs (and think repeating the docstrings is useless as documentation: those interested in docstrings _can_ actually read code).

there's probably something to say for both opinions. 
I'm not actually sure plone.app.event **uses** much of these extensions, most seems real documentation, but I haven't time now to look it all through.

In any case, it's a carfuffle to include documentation that relies on these sphinx-extensions, so needs some review/thinking. In the meantime I will put in a reference to https://ploneappevent.readthedocs.org/en/latest/

**Comment by polyester** [comment]
update: the autodoc does not work, only on one(!) page, namely https://ploneappevent.readthedocs.org/en/latest/api/browser/event_view.html

all the other ones in https://ploneappevent.readthedocs.org/en/latest/api/ are broken. So I would suggest disabling the sphinx-extensions and manually documenting the api (however terse)

**Comment by thet** [comment]
I'll give that a try. @polyester , did you build the docs in plone.app.event or with papyrus? if yes, how do i do that?

**Comment by polyester** [comment]
I haven't built the docs yet in papyrus, because of the sphinx-extension issues mentioned above. I did try to run the included buildout of plone.app.event, but that errored out. (the usual fight between various setuptools/zc.buildout version... Could probably fix that locally but time-stretched)

I just checked the docs on readthedocs, and noticed that they are failing there for the autodoc stuff.

Including plain rst docs into papyrus is easy, documented at https://github.com/plone/papyrus/blob/5.0/docs/add_external_docs.rst
I can make a preliminary branch later today/tonight to show how it's done.
